### ISSUE TITLE
Remove empty line for at rules

### ISSUE THREAD

**Issue by paweljanuszkiewicz** [tonik/stylelint-config-scss#8]
Linter force to adding empty line with at rule, block-closing-brace-newline-after
```scss
@if map-has-key($breakpoints, $name) {
  @return map-get($breakpoints, $name);
}

@else {
  @error "ERROR: Specified breakpoint does not exist";
}
```

Throws error for:
```scss
@if map-has-key($breakpoints, $name) {
  @return map-get($breakpoints, $name);
} @else {
  @error "ERROR: Specified breakpoint does not exist";
}
```

**Comment by jedrzejchalubek** [comment]
An only way to achieve this is to ignore entirely @at-rules which leads to event worst formatting scenario (https://stylelint.io/user-guide/rules/block-closing-brace-newline-after#optional-secondary-options):

```scss
@if ($var) { color: pink; } @else { color: blue; }
```

I think we will leave this as it is
